# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [fix_md_script]
highlighter: none
# Site settings
title:
  bg: VoxForge - Bulgarian
  ca: VoxForge - Catalan
  de: VoxForge - German
  el: VoxForge - Greek
  en: VoxForge - Free Speech... Recognition
  es: VoxForge - libertad de expresión
  fr: VoxForge - Voix Libre
# word 'language' in local language
languagesLocal:
  bg: Език
  ca: Idioma
  de: Sprachen
  el: Γλώσσες
  en: Languages
  fr: Langues
  es: Idiomas
# localized language name
languageName:
  bg: Български
  ca: Catalan
  de: Deutsch
  el: Ελληνικά
  en: English
  fr: Français
  es: Español
languageEnglish:
  bg: Bulgarian
  ca: Catalan
  de: German
  el: Greek
  en: English
  fr: French
  es: Spanish
supportedLanguages:
  EN: English
  FR: French
email: contact@voxforge.org
index:
  bg: home
  ca: home
  de: home
  el: Σπίτι
  en: home
  de: homeindex???
  fr: accueil
  es: boenosdias
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://voxforge.org" # the base hostname & protocol for your site
url: "http://voxforge.github.io" # the base hostname & protocol for your site
collections:
  faqfolder:
    output: true
    title: FAQs
    permalink: /faq/:path/ # this is for faq item path
plugins:
  - jekyll-redirect-from
