# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  bg: VoxForge - Bulgarian
  ca: VoxForge - Catalan
  en: VoxForge - Free Speech... Recognition
  es: VoxForge - libertad de expresión
  fr: VoxForge - Voix Libre
languagesLocal:
  bg: Език
  ca: Idioma
  en: Languages
  fr: Langues
  es: Idiomas
languageName:
  bg: Bulgarian
  ca: Catalan
  en: English
  fr: Français
  es: Español
email: cgontact@voxforge.org
index:
  bg: home
  ca: home
  en: home
  fr: accueil
  es: boenosdias
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://voxforge.org" # the base hostname & protocol for your site
collections:
  faq:
    output: true
    title: FAQs
    permalink: /faq/:path/ # this is for faq item path
gems:
  - jekyll-redirect-from
