# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [fix_md_script]
# Site settings
title:
  en: VoxForge - Free Speech... Recognition
  es: VoxForge - libertad de expresión
  fr: VoxForge - Voix Libre
# word 'language' in local language
languagesLocal:
  en: Languages
  fr: Langues
  es: Idiomas
# localized language name
languageName:
  en: English
  fr: Français
  es: Español
languageEnglish:
  en: English
  fr: French
  es: Spanish
# TODO temporary until I figure out how to set up multiple languages in javascript app...
supportedLanguages:
  EN: English
  FR: French
  ES: Spanish
email: contact@voxforge.org
index:
  en: home
  fr: accueil
  es: boenosdias
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://voxforge.github.io" # the base hostname & protocol for your site
url: "https://jekyll_voxforge.org" # the base hostname & protocol for your site
collections:
  faqfolder:
    output: true
    title: FAQs
    permalink: /faq/:path/ # this is for faq item path
plugins:
  - jekyll-redirect-from

