# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [fix_md_script]

# Site settings
title:
  en: VoxForge - Free Speech... Recognition
  es: VoxForge - libertad de expresión
  fr: VoxForge - Voix Libre

# word 'language' in local language
languagesLocal:
  en: Languages
  fr: Langues
  es: Idiomas

# localized language name
languageName:
  en: English
  fr: Français
  es: Español
# hover language name translated to English
languageEnglish:
  en: English
  fr: French
  es: Spanish

email: contact@voxforge.org
index:
  en: home
  fr: accueil
  es: boenosdias
baseurl: "" # the subpath of your site, e.g. /blog

# redirects use this url:
url: "https://voxforge.github.io" # the base hostname & protocol for your site
#url: "https://jekyll_voxforge.org" # dev

# Note: In Jekyll 2, any URL constructed from the permalink: field had a 
# trailing slash (/) added to it automatically. Jekyll 3 no longer adds a
# trailing slash automatically to permalink: URLs
# see: https://jekyllrb.com/docs/upgrading/2-to-3/

permalink: /:lang/:ref # required for links to work properly on Github
# add trailing slash to permalinks for debugging with Apache2 and self signed SSL certificate
# note: messes up manifest path, expects manifest.json at https://jekyll_voxforge.org/en/read/manifest.json
# when it should be https://jekyll_voxforge.org/en/manifest.json
#permalink: /:lang/:ref/ # !!!!!! for debugging with jekyll locally


collections:
  faqs:
    output: true
    title: FAQs

# see: https://help.github.com/articles/redirects-on-github-pages/
plugins:
  - jekyll-redirect-from

