# some updates to this file require restart of jekyll server

# default language
lang: en
appversion: "0.3.2"
appversion_text: "App ver."

username_label: Username
anonymous: anonymous
anonymous_submission: (leave blank to submit anonymously)
profile_info: Profile Info
default_value: not selected

# Yes and No must be in quotes, otherwise evaluates to true/false
# can't use 'yes' or 'no' as variable names in YAML
localized_variable:
  lv_yes: "Yes"
  lv_no: "No"
  other: "Other"

please_select: Please Select
speaker_characteristics: Speaker Characteristics

gender:
  label: Gender
  selection:
    - Male
    - Female
    - Other

# US - COPPA - children under 13yrs need parental consent for collection of
# personal information; therefore don't accept submissions from them
age:
  label: Age
  selection:
    - { value: '13 - 17', old_value: 'Youth', desc: 'Youth' }
    - { value: '18 - 29', old_value: 'Adult', desc: 'Adult' }
    - { value: '30 - 39', old_value: 'Adult', desc: 'Adult' }
    - { value: '40 - 49', old_value: 'Adult', desc: 'Adult' }
    - { value: '50 - 59', old_value: 'Adult', desc: 'Adult' }
    - { value: '60 - 64', old_value: 'Adult', desc: 'Adult' }
    - { value: '65 - 74', old_value: 'Senior', desc: 'Senior' }
    - { value: '> 75', old_value: 'Senior', desc: 'Senior' }

# - leave a blank line between groupings of hash/objects; otherwise liquid does 
# not parse properly
# - Yes and No must be in quotes, otherwise evaluates to true/false
native_speaker:
  label: Native Speaker?
  popup_link: 'https://en.wikipedia.org/wiki/First_language'
  popup_text: someone who speaks a language as his or her first language or mother tongue.
  selection:
    - "Yes"
    - "No"

first_language:
  label: First Language
  popup_link: https://en.wikipedia.org/wiki/First_language
  popup_text: language that a person has been exposed to from birth or within the critical period.
  other_label: Enter first language

dialect:
  label: Pronunciation Dialect
  popup_link: https://en.wikipedia.org/wiki/Dialect
  popup_text: variety of a language that is a characteristic of a particular group of the language's speakers.
  selection:
# major geographical region e.g. North American [array containing subdialects e.g. canadian English...]
  - [Other, [Other]]
  other_label: Enter dialect

# no default required for sub-dialect

recording_information: Recording Information

microphone:
  label: Microphone Type
  selection:
    - Analog Microphone
    - USB Microphone
    - Laptop Builtin Microphone
    - Smartphone
    - Tablet
    - Microphone Array/Far Field Mic
    - Other
  other_label: Enter microphone type

recording_location:
  label: Recording Location
  selection:
    - Indoors
    - Outdoors
    - Vehicle
    - Other
  other_label: Enter location

background_noise:
  label: Is There Background Noise?
  selection:
    - "Yes"
    - "No"

# first two elements must be low volume;
# View.prototype.noiseTurnOffVad() assumes this in determining whether to disable VAD
# when there's too much noise
noise_volume:
  label: Noise Volume
  selection:
    - Low - constant
    - Low - intermitent
    - Moderate - constant
    - Moderate - intermitent
    - Loud - constant
    - Loud - intermitent

noise_type:
  label: Noise Type
  selection:
    - Crowd
    - Electronic Equipment
    - Echo
    - Fan/Air Conditioner
    - Machinery
    - Nature sounds
    - Talking
    - Music
    - Traffic
    - TV
    - Video
    - Weather Related (wind/rain...)
    - Other
  other_label: Enter noise type

license:
  label: License
  popup:
    title: Creative Commons Licences
    link: https://creativecommons.org/licenses/
    hover_text: >
      CC0 1.0 - Creative Commons Public Domain Dedication;
      CC BY 4.0 - Creative Commons Attribution;
      CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike;
      GPLv3 - GNU General Public License.
    text:  > 
      <b>CC0 1.0 - Creative Commons Public Domain Dedication</b> you dedicate this work to the
      public domain by waiving all of your rights to the work worldwide
      under copyright law.  If you don't know which license to choose, choose: <b>CC0</b>.<br>
      <b>CC BY 4.0 - Creative Commons Attribution</b>  This license lets others distribute, remix, 
      tweak, and build upon your work, even commercially, as long as they 
      credit you for the original creation.<br>
      <b>CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike </b>  This license lets others 
      remix, tweak, and build upon your work even for commercial purposes, 
      as long as they credit you and license their new creations under the 
      identical terms.  <br>
      <b>GPLv3 GNU General Public License</b> similar to CC BY-SA, but made for software... used by
      VoxForge 1.0 corpus.
  selection_default: { value: 'CC0',  item: 'CC0 - Creative Commons 1.0 - No rights Reserved (default)' }
  selection:
    - { value: 'CC_BY',     option: 'CC BY - Creative Commons - Attribution 4.0' }
    - { value: 'CC_BY-SA',  option: 'CC BY-SA - Creative Commons Attribution-ShareAlike 4.0' }
    - { value: 'GPLv3',     option: 'GPLv3 - GNU General Public License version 3' }
  full_license:
    CC0:
      title: CC0 1.0 - Creative Commons CC0 1.0 Universal Public Domain Dedication
      link: "https://creativecommons.org/publicdomain/zero/1.0/"
      attribution: "_year_ VoxForge Speech Recording by:"
      text:
        - The person who associated a work with this deed has dedicated the work 
        - to the public domain by waiving all of his or her rights to the work
        - worldwide under copyright law, including all related and neighboring 
        - rights, to the extent allowed by law.
        - ""
        - You can copy, modify, distribute and perform the work, even for 
        - commercial purposes, all without asking permission. 
        - ""
        - You should have received a copy of the CC0 legalcode along with this
      text_last: work.  If not, see
    CC_BY:
      title: CC BY 4.0 - Creative Commons Attribution 4.0 International Public License
      link: "https://creativecommons.org/licenses/by/4.0/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - This Speech Recording is licensed under a Creative Commons Attribution 4.0
        - Unported License.
        - ""
        - "You are free to:"
        - ""
        - Share — copy and redistribute the material in any medium or format
        - Adapt — remix, transform, and build upon the material
        - for any purpose, even commercially.
        - ""
        - "Under the following terms:"
        - ""
        - Attribution - You must give appropriate credit, provide a link to the 
        - license, and indicate if changes were made. You may do so in any 
        - reasonable manner, but not in any way that suggests the licensor 
        - endorses you or your use.
        - ""
        - You should have received a copy of the CC BY 4.0 legalcode along with 
      text_last: this work.  If not, see
    CC_BY-SA:
      title: CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike 4.0 International Public License
      link: "https://creativecommons.org/licenses/by-sa/4.0/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - This Speech Recording is licensed under a Creative Commons 
        - Attribution 4.0 Unported License.
        - ""
        - "You are free to:"
        - ""
        - Share — copy and redistribute the material in any medium or format
        - Adapt — remix, transform, and build upon the material
        - for any purpose, even commercially.
        - ""
        - "Under the following terms:"
        - ""
        - Attribution - You must give appropriate credit, provide a link to the 
        - license, and indicate if changes were made. You may do so in any 
        - reasonable manner, but not in any way that suggests the licensor 
        - endorses you or your use.
        - ""
        - ShareAlike — If you remix, transform, or build upon the material, 
        - you must distribute your contributions under the same license as 
        - the original.
        - ""
        - You should have received a copy of the CC BY-SA 4.0 legalcode along 
      text_last: with this work.  If not, see
    GPLv3:
      title: GPLv3 - GNU General Public License.
      link: "https://www.gnu.org/licenses/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - "This program is free software: you can redistribute it and/or modify"
        - it under the terms of the GNU General Public License as published by
        - the Free Software Foundation, either version 3 of the License, or
        - (at your option) any later version.
        - ""
        - This program is distributed in the hope that it will be useful,
        - but WITHOUT ANY WARRANTY; without even the implied warranty of
        - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        - GNU General Public License for more details.
        - ""
        - You should have received a copy of the GNU General Public License
      text_last: along with this program.  If not, see

num_prompts:
  label: Number of prompts to read

instructions:
  label: Instructions
  lines:
    - 1. Click <b>Record</b> to start, reading aloud only the sentence shown in the box below (which will display after record button is pressed)
    - 2. When done speaking, <b>wait</b> a moment, then click <b>Stop</b>.
    - 3. <b>Review</b> any recordings with warnings.    
  lastline: >
    4. When all prompts are completed, click <b>Upload</b> to either
    upload to VoxForge server or save to browser storage for later uploading.

# TODO not supporting Edge yet... Edge needs to support FormData
# convert to popup for Edge browsers only...
#  edge:
#    mouse_over_text: For Microsoft Edge browser, click here to see how to give your browser permission to use your microphone.
#  popup:
#     title: Windows - How to give your Edge browser permission to use your microphone
#      link: https://privacy.microsoft.com/en-us/windows-10-camera-and-privacy
#      text:  > 
#        1. Go to Start, then select Settings > Privacy > Microphone.<br> 
#        2. Choose your preferred setting for Let apps use my microphone.<br>
#        3. Under Choose apps that can use your microphone, turn on the individual setting for the Edge browser.<br>

# TODO convert to icons so that no need to translate
controls:
  record: Record
  stop: Stop
  upload: Upload
  play: Play

browser_support:
  no_worker_message: >
    "Your browser does not support service or web workers, please
    upgrade to a current version of a Free and Open Source browser such as 
    Chrome or Firefox."
  no_indexedDB_message: >
    "Your browser does not support indexedDB for offline storage of 
    submissions, please upgrade to a current version of a Free and Open 
    Source browser such as Chrome or Firefox."
  no_formDataSupport_message: >
    "Browser does not support FormData... please install 
    a current version of a Free and Open Source browser such as Chrome or 
    Firefox"
  no_edgeSupport_message: >
    "Microsoft browsers not supported... please install 
    a current version of a Free and Open Source browser such as Chrome or 
    Firefox"

# localstorage_message - <br> or \n line breaks don't work...
alert_message:
  localstorage_message: >
    Cannot connect to server.
    Submission saved to browser storage.
    Will upload with next submission made with connection to server. 
  browsercontains_message: >
    Your browser storage contains
  uploaded_message: >
    uploaded to VoxForge Server
  serviceworker: serviceworker
  webworker: webworker
  workernotfound: worker type not found
  submission_singular: submission
  submission_plural: submissions

  getUserMedia_error: >
    Could not get audio input... make sure your microphone is connected to your 
    computer.  Your browser is giving this error message:
  notHtml5_error: >
    Your device does not support the HTML5 API needed to record audio
  rec_info_activated: >
    "Recording Information" section activated under "Profile Info".  This uses
    a simple timer since your last submission to remind you to confirm your
    "Recording Information" settings are still valid.  This can
    be disabled in Settings.
  time_limit: >
    It's been a while since last your submission: please review your
    Recording Information settings and, if necessary, update your
    Location and Noise Levels.
  location_change: >
    Location Change: please review your Recording Information settings and,
    if necessary, update your Location and Noise Level/Type.
  noise_Turn_Off_Vad: >
    Background noise present.  You might need to disable VAD (Voice Activity
    Detection) in Settings, then delete and re-record your last prompt.

speechCharacteristics:
  audio_too_loud_short: 'Error: too loud!'  
  audio_too_loud_text: >
    Your recording is too loud!
    Please reduce your microphone volume,
    then delete this recording and re-record the prompt.
  audio_too_soft_short: 'Warning: not loud enough!'   
  audio_too_soft_text: >
    Your recording levels are too low!
    Please increase your microphone volume,
    then delete this prompt recording and re-record it.
  no_trailing_silence_short: 'Warning: no trailing silence.'
  no_trailing_silence_text: >
    You may have not left enough trailing silence (i.e. clicked
    'stop' too early)
    Please review and make sure there is some silence (at least
    1/4 of a second) at end of this recording.
    If not, delete and re-record the prompt.
  no_speech_short: 'Error : no speech.'
  no_speech_text: >
    No Speech (or microphone volume too low).
    Please increase microphone volume,
    then delete and re-record this prompt.
    
settings:
  title: Settings
  none: none
  recording_information_text: Reminders
  recording_information_text_2: >
   (to remind you to make sure that your Recording Information settings are still 
   valid, if you changed locations since your last recording).
  display_record_info: >
    Display "Recording Information" section.
  recording_time_reminder: >
    use the time since your last recording to determine when to remind.
  recording_geolocation_reminder: >
    use GPS to monitor for change in location to determine when to remind (resource intensive).
  resource_intensive_text: Resource intensive functions
  resource_intensive_text_2: >
    (disable these to improve recording quality on low powered devices)
  vad_run: Voice Activity Detection (VAD)
  auto_gain: Automatic Volume Adjuster
  audio_visualizer: Audio visualizer
  waveform_display: Waveform display for each recording  
  saved_submissions: Waiting to upload (in browser storage)
  uploaded_submissions: Uploaded submissions
  system_information_text: System information
  system_information_text_2: (included in submission)
  ua_string: User Agent String
  debug_text: Browser audio settings
 
