# some updates to this file require restart of jekyll server

# default language
lang: en

username_label: Username
anonymous: anonymous
anonymous_submission: (leave blank to submit anonymously)
profile_info: Profile Info
default_value: not selected

# Yes and No must be in quotes, otherwise evaluates to true/false
# can't use 'yes' or 'no' as variable names in YAML
localized_variable:
  lv_yes: "Yes"
  lv_no: "No"
  other: "Other"

please_select: Please Select
speaker_characteristics: Speaker Characteristics

gender:
  label: Gender
  selection:
    - Male
    - Female
    - Other

age:
  label: Age
  selection:
    - { value: '< 20', old_value: 'Youth' }
    - { value: '20 - 29', old_value: 'Adult' }
    - { value: '30 - 39', old_value: 'Adult' }
    - { value: '40 - 49', old_value: 'Adult' }
    - { value: '50 - 59', old_value: 'Adult' }
    - { value: '60 - 69', old_value: 'Adult' }
    - { value: '70 - 79', old_value: 'Senior' }
    - { value: '80 - 89', old_value: 'Senior' }
    - { value: '> 89', old_value: 'Senior' }

# - leave a blank line between groupings of hash/objects; otherwise liquid does 
# not parse properly
# - Yes and No must be in quotes, otherwise evaluates to true/false
native_speaker:
  label: Native Speaker?
  popup_link: 'https://en.wikipedia.org/wiki/First_language'
  popup_text: someone who speaks a language as his or her first language or mother tongue.
  selection:
    - "Yes"
    - "No"

first_language:
  label: First Language
  popup_link: https://en.wikipedia.org/wiki/First_language
  popup_text: language that a person has been exposed to from birth or within the critical period.
  other_label: Other First Language

dialect:
  label: Pronunciation Dialect
  popup_link: https://en.wikipedia.org/wiki/Dialect
  popup_text: variety of a language that is a characteristic of a particular group of the language's speakers.
  selection:
# major geographical region e.g. North American [array containing subdialects e.g. canadian English...]
  - [Other, [Other]]
  other_label: Other Dialect

# no default required for sub-dialect

recording_information: Recording Information

microphone:
  label: Microphone Type
  selection:
    - Analog Microphone
    - USB Microphone
    - Laptop Builtin Microphone
    - Smartphone
    - Tablet
    - Microphone Array/Far Field Mic
    - Other
  other_label: Other Microphone Type

recording_location:
  label: Recording Location
  selection:
    - Indoors
    - Outdoors
    - Vehicle
    - Other
  other_label: Other Recording Location

background_noise:
  label: Is There Background Noise?
  selection:
    - "Yes"
    - "No"

# first two elements must be low volume;
# View.prototype.noiseTurnOffVad() assumes this in determining whether to disable VAD
# when there's too much noise
noise_volume:
  label: Noise Volume
  selection:
    - Low - constant
    - Low - intermitent
    - Moderate - constant
    - Moderate - intermitent
    - Loud - constant
    - Loud - intermitent

noise_type:
  label: Noise Type
  selection:
    - Crowd
    - Electronic Equipment
    - Echo
    - Fan/Air Conditioner
    - Machinery
    - Nature sounds
    - Talking
    - Music
    - Traffic
    - TV
    - Video
    - Weather Related (wind/rain...)
    - Other
  other_label: Other Type of Noise

license:
  label: License
  popup:
    title: Creative Commons Licences
    link: https://creativecommons.org/licenses/
    hover_text: >
      CC0 1.0 - Creative Commons Public Domain Dedication;
      CC BY 4.0 - Creative Commons Attribution;
      CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike;
      GPLv3 - GNU General Public License.
    text:  > 
      <b>CC0 1.0 - Creative Commons Public Domain Dedication</b> you dedicate this work to the
      public domain by waiving all of your rights to the work worldwide
      under copyright law.  If you don't know which license to choose, choose: <b>CC0</b>.<br>
      <b>CC BY 4.0 - Creative Commons Attribution</b>  This license lets others distribute, remix, 
      tweak, and build upon your work, even commercially, as long as they 
      credit you for the original creation.<br>
      <b>CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike </b>  This license lets others 
      remix, tweak, and build upon your work even for commercial purposes, 
      as long as they credit you and license their new creations under the 
      identical terms.  <br>
      <b>GPLv3 GNU General Public License</b> similar to CC BY-SA, but made for software... used by
      VoxForge 1.0 corpus.
  selection_default: { value: 'CC0',  item: 'CC0 - Creative Commons 1.0 - No rights Reserved (default)' }
  selection:
    - { value: 'CC_BY',     option: 'CC BY - Creative Commons - Attribution 4.0' }
    - { value: 'CC_BY-SA',  option: 'CC BY-SA - Creative Commons Attribution-ShareAlike 4.0' }
    - { value: 'GPLv3',     option: 'GPLv3 - GNU General Public License version 3' }
  full_license:
    CC0:
      title: CC0 1.0 - Creative Commons CC0 1.0 Universal Public Domain Dedication
      link: "https://creativecommons.org/publicdomain/zero/1.0/"
      attribution: "_year_ VoxForge Speech Recording by:"
      text:
        - The person who associated a work with this deed has dedicated the work 
        - to the public domain by waiving all of his or her rights to the work
        - worldwide under copyright law, including all related and neighboring 
        - rights, to the extent allowed by law.
        - ""
        - You can copy, modify, distribute and perform the work, even for 
        - commercial purposes, all without asking permission. 
        - ""
        - You should have received a copy of the CC0 legalcode along with this
      text_last: work.  If not, see
    CC_BY:
      title: CC BY 4.0 - Creative Commons Attribution 4.0 International Public License
      link: "https://creativecommons.org/licenses/by/4.0/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - This Speech Recording is licensed under a Creative Commons Attribution 4.0
        - Unported License.
        - ""
        - "You are free to:"
        - ""
        - Share — copy and redistribute the material in any medium or format
        - Adapt — remix, transform, and build upon the material
        - for any purpose, even commercially.
        - ""
        - "Under the following terms:"
        - ""
        - Attribution - You must give appropriate credit, provide a link to the 
        - license, and indicate if changes were made. You may do so in any 
        - reasonable manner, but not in any way that suggests the licensor 
        - endorses you or your use.
        - ""
        - You should have received a copy of the CC BY 4.0 legalcode along with 
      text_last: this work.  If not, see
    CC_BY-SA:
      title: CC BY-SA 4.0 - Creative Commons Attribution-ShareAlike 4.0 International Public License
      link: "https://creativecommons.org/licenses/by-sa/4.0/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - This Speech Recording is licensed under a Creative Commons 
        - Attribution 4.0 Unported License.
        - ""
        - "You are free to:"
        - ""
        - Share — copy and redistribute the material in any medium or format
        - Adapt — remix, transform, and build upon the material
        - for any purpose, even commercially.
        - ""
        - "Under the following terms:"
        - ""
        - Attribution - You must give appropriate credit, provide a link to the 
        - license, and indicate if changes were made. You may do so in any 
        - reasonable manner, but not in any way that suggests the licensor 
        - endorses you or your use.
        - ""
        - ShareAlike — If you remix, transform, or build upon the material, 
        - you must distribute your contributions under the same license as 
        - the original.
        - ""
        - You should have received a copy of the CC BY-SA 4.0 legalcode along 
      text_last: with this work.  If not, see
    GPLv3:
      title: GPLv3 - GNU General Public License.
      link: "https://www.gnu.org/licenses/"
      attribution: "VoxForge Speech Recording, Copyright (C) _year_"
      text:
        - "This program is free software: you can redistribute it and/or modify"
        - it under the terms of the GNU General Public License as published by
        - the Free Software Foundation, either version 3 of the License, or
        - (at your option) any later version.
        - ""
        - This program is distributed in the hope that it will be useful,
        - but WITHOUT ANY WARRANTY; without even the implied warranty of
        - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        - GNU General Public License for more details.
        - ""
        - You should have received a copy of the GNU General Public License
      text_last: along with this program.  If not, see

num_prompts:
  label: Number of prompts to read


instructions:
  label: Instructions
  lines:
    - 1. Click <b>Record</b> to start, saying only the words that appear in the box below.
    - 2. Click <b>Stop</b> when completed.
  lastline: >
    3. When done, click <b>Upload</b> to send your recordings to VoxForge server.


# TODO not supporting Edge yet... Edge needs to support FormData
# convert to popup for Edge browsers only...
#  edge:
#    mouse_over_text: For Microsoft Edge browser, click here to see how to give your browser permission to use your microphone.
#  popup:
#     title: Windows - How to give your Edge browser permission to use your microphone
#      link: https://privacy.microsoft.com/en-us/windows-10-camera-and-privacy
#      text:  > 
#        1. Go to Start, then select Settings > Privacy > Microphone.<br> 
#        2. Choose your preferred setting for Let apps use my microphone.<br>
#        3. Under Choose apps that can use your microphone, turn on the individual setting for the Edge browser.<br>

controls:
  record: Record
  stop: Stop
  upload: Upload
  play: Play

browser_support:
  no_worker_message: >
    "Your browser does not support service or web workers, please
    upgrade to a current version of a Free and Open Source browser such as 
    Chrome or Firefox."
  no_indexedDB_message: >
    "Your browser does not support indexedDB for offline storage of 
    submissions, please upgrade to a current version of a Free and Open 
    Source browser such as Chrome or Firefox."
  no_formDataSupport_message: >
    "Browser does not support FormData... please install 
    a current version of a Free and Open Source browser such as Chrome or 
    Firefox"
  no_edgeSupport_message: >
    "Microsoft browsers not supported... please install 
    a current version of a Free and Open Source browser such as Chrome or 
    Firefox"

# localstorage_message - <br> or \n line breaks don't work...
alert_message:
  localstorage_message: >
    Cannot connect to server.
    Submission saved to browser storage.
    Will upload with next submission made with connection to server. 
  browsercontains_message: >
    Your browser storage contains
  uploaded_message: >
    uploaded to VoxForge Server
  serviceworker: serviceworker
  webworker: webworker
  workernotfound: worker type not found
  submission_singular: submission
  submission_plural: submissions
  audio_too_loud: >
    Your recording is too loud!<br>
    Please reduce your microphone volume<br>
    delete this recording and re-record the prompt
  audio_too_soft: >
    Your recording levels are too low!<br>
    Please increase your microphone volume, 
    then delete this prompt recording and re-record it.
  no_trailing_silence: >
    Not enough trailing silence - you clicked 'stop' too early! <br>
    You did not leave enough silence at the end of your recording, or you
    cut-off the end of your recording<br>
    Please delete and re-record this prompt.
  no_speech: >
    No Speech or recording volume too low<br>
    Please increase your microphone volume,
    then delete and re-record this prompt.
  audio_too_loud_autogain: >
    Your recording is too loud!<br>
    Automatically decreasing volume.<br>
    Please delete this recording and re-record the prompt.
  audio_too_soft_autogain: >
    Your recording levels are too low!<br>
    Automatically increasing volume.<br>
    Please delete this recording and re-record the prompt.
  no_speech_autogain: >
    No Speech or recording volume too low.<br>
    Automatically increasing volume.<br>
    Please delete this recording and re-record the prompt.
  getUserMedia_error: >
    Could not get audio input... make sure your microphone is connected to your 
    computer.  Your browser is giving this error message:
  notHtml5_error: >
    Your device does not support the HTML5 API needed to record audio
  rec_info_activated: >
    "Recording Information" section activated under "Profile Info"
    (can be disabled in Settings).
  time_limit: >
    It's been a while since last your submission: please review your
    Recording Information settings and, if necessary, update your
    Location and Noise Levels.
  location_change: >
    Location Change: please review your Recording Information settings and,
    if necessary, update your Location and Noise Levels.
    
settings:
  title: Settings
  include_heading: Include in Submission
  ua_string: User Agent String
  debug: Debug Information
  other_heading: Other
  display_record_info: >
    Recording Information (needs to be updated each time location or
    noise characteristics change)
  vad_run: VAD enabled (Voice Activity Detection)
  recording_location_reminder: Recording Location reminder (uses geolocation or time since last submission)

# TODO no longer used
ua_string:
  label: User Agent String
  link: http://www.useragentstring.com
  hover_text:  > 
    When your web browser makes a request to a website, it also sends a User 
    Agent string.  This string contains information about your browser name, 
    operating system, device type, etc.
    The VoxForge app collects this information to help troubleshoot and
    determine which devices work best with this app.
  popup:
    title: Collect User Agent String Information
    link: http://www.useragentstring.com
    hover_text: >
      Include User Agent string with submission
    text:  > 
      When your web browser makes a request to a website, it also sends a User 
      Agent string.  This string contains information about your browser name, 
      operating system, device type, etc.<br>
      The VoxForge app collects this information to help troubleshoot and
      determine which devices work best with this app.<br>
  selection_default: { value: 'Yes',  item: 'Yes' }
  selection:
    - { value: 'No',  option: 'No' }
